### PR TITLE
Cleaning out old gmake build system

### PR DESCRIPTION
**Pull request by arunchawla-NOAA**
Here is an example clean up. I removed the Conf directory, the old shell script based gmake and the old readme. Also updated version numbers based on the tags

### CODE REVIEW

**Comment by aerorahul** [comment]
why did you close the PR?

**Comment by arunchawla-NOAA** [comment]
Because I do not know what I am doing obviously

**Comment by arunchawla-NOAA** [comment]
I removed the file and pushed it to the branch

**Comment by DusanJovic-NOAA** [comment]
If you are going to chnage README.md please consider removing "| PGI". We do not support PGI compiler.

**Comment by DusanJovic-NOAA** [comment]
The latest installed version I can find is bacio/2.0.3, which means this version should be 2.1.0, not 2.2.0. Is anyone aware of 2.1.x being available somewhere?

**Comment by arunchawla-NOAA** [comment]
There is a tag with 2.1.0 and the old readme (that I conveniently deleted)
said 2.1.0 had some updates.
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Pull request merged**
