### PR TITLE
More testing, removed unused code in byteswap.c

### PR DESCRIPTION
**Pull request by edwardhartnett**
This is a follow-on to PR #63. 

More testing.

Removed a bunch of static functions in byteswap.c that were not being used.

Part of #33 
Part of #38
Part of #59
Part of #68

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, with these tests, we get better code coverage. I'm not sure if there is much more testing to do here...

image

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA and @BrianCurtis-NOAA please review this PR so I can get it merged. Thanks!

**Review by Hang-Lei-NOAA — APPROVED** [review]
Could you please interpret why you almost removed all the loops in byteswap.c ?

**Comment by edwardhartnett** [comment]
See #68. All the code removed from byteswap.c were static functions that were never called. Since they are static functions, they cannot be called by any users, only by code in the same file. Since they are never called, we know the code is never used.

There were three different varieties of the byteswap functions, and only one set is needed or used.

**Review by BrianCurtis-NOAA — APPROVED** [review]
In byteswap.c I'm assuming the functions removed are not used in anything?

I see i'm late to the party. nevermind.

**Comment by edwardhartnett** [comment]
There was lots of dead code in bacio!

Code size can be reduced further - the remaining C code is just two copies of the same function, with different argument types. They can easily be combined... That will be a future PR.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I see this, Thanks

**Pull request merged**
